print("Hello Git")
print("This is version 3")
print("feature branch development")
<<<<<<< HEAD
print("master branch development")
=======
print("feature branch second change")
>>>>>>> feature
print("master remote practise")
print("change made directly on github")
print("remote divergent change")
print("master side rebase change")
print("team:update preprocessing pipeline")
print("new master change for rebase")
print("team:update model configuartion")
print("feature: fast forward practice")
print("feature: fast forward practice")
print("feature:no fast forward practice")
print("feature: model validation")
print("team: another developer change")
print("another developer changed master")
print("squash commit 1")
print("squash commit 2")
print("squash commit 3")